[package]
name = "mdbook-gemini"
version = "0.1.0"
authors = ["Érico Nogueira <ericonr@disroot.org>"]
license = "MIT"
edition = "2018"

[dependencies]
mdbook = "0.4"
env_logger = "0.6"
log = "0.4"
pulldown-cmark = "0.7.0"
